// flow-typed signature: 17c9cf986dcd4fa302f12f6135f43953
// flow-typed version: <<STUB>>/sematable_v^1.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sematable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sematable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sematable/lib/actions' {
  declare module.exports: any;
}

declare module 'sematable/lib/common' {
  declare module.exports: any;
}

declare module 'sematable/lib/dataTable' {
  declare module.exports: any;
}

declare module 'sematable/lib/Filter' {
  declare module.exports: any;
}

declare module 'sematable/lib/index' {
  declare module.exports: any;
}

declare module 'sematable/lib/PageSize' {
  declare module.exports: any;
}

declare module 'sematable/lib/Pagination' {
  declare module.exports: any;
}

declare module 'sematable/lib/reducer' {
  declare module.exports: any;
}

declare module 'sematable/lib/SelectAllHeader' {
  declare module.exports: any;
}

declare module 'sematable/lib/selectors' {
  declare module.exports: any;
}

declare module 'sematable/lib/SelectRow' {
  declare module.exports: any;
}

declare module 'sematable/lib/sematable' {
  declare module.exports: any;
}

declare module 'sematable/lib/SortableHeader' {
  declare module.exports: any;
}

declare module 'sematable/lib/Table' {
  declare module.exports: any;
}

declare module 'sematable/lib/TableNoData' {
  declare module.exports: any;
}

declare module 'sematable/lib/TableRow' {
  declare module.exports: any;
}

declare module 'sematable/stories/bootstrap/v3.3.7/js/bootstrap' {
  declare module.exports: any;
}

declare module 'sematable/stories/bootstrap/v3.3.7/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'sematable/stories/bootstrap/v3.3.7/js/npm' {
  declare module.exports: any;
}

declare module 'sematable/stories/bootstrap/v4.0.0/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'sematable/stories/button/StoryButton' {
  declare module.exports: any;
}

declare module 'sematable/stories/Checkbox' {
  declare module.exports: any;
}

declare module 'sematable/stories/common/users' {
  declare module.exports: any;
}

declare module 'sematable/stories/common/UsersTable' {
  declare module.exports: any;
}

declare module 'sematable/stories/common/YesNo' {
  declare module.exports: any;
}

declare module 'sematable/stories/default/StoryDefault' {
  declare module.exports: any;
}

declare module 'sematable/stories/default/StorySelectable' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/EditableCell' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/EditableSimpleCell' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/EditableUsersTable' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/EditibleUsersTable' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/StoryEditable' {
  declare module.exports: any;
}

declare module 'sematable/stories/editable/YesNo' {
  declare module.exports: any;
}

declare module 'sematable/stories/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sematable/lib/actions.js' {
  declare module.exports: $Exports<'sematable/lib/actions'>;
}
declare module 'sematable/lib/common.js' {
  declare module.exports: $Exports<'sematable/lib/common'>;
}
declare module 'sematable/lib/dataTable.js' {
  declare module.exports: $Exports<'sematable/lib/dataTable'>;
}
declare module 'sematable/lib/Filter.js' {
  declare module.exports: $Exports<'sematable/lib/Filter'>;
}
declare module 'sematable/lib/index.js' {
  declare module.exports: $Exports<'sematable/lib/index'>;
}
declare module 'sematable/lib/PageSize.js' {
  declare module.exports: $Exports<'sematable/lib/PageSize'>;
}
declare module 'sematable/lib/Pagination.js' {
  declare module.exports: $Exports<'sematable/lib/Pagination'>;
}
declare module 'sematable/lib/reducer.js' {
  declare module.exports: $Exports<'sematable/lib/reducer'>;
}
declare module 'sematable/lib/SelectAllHeader.js' {
  declare module.exports: $Exports<'sematable/lib/SelectAllHeader'>;
}
declare module 'sematable/lib/selectors.js' {
  declare module.exports: $Exports<'sematable/lib/selectors'>;
}
declare module 'sematable/lib/SelectRow.js' {
  declare module.exports: $Exports<'sematable/lib/SelectRow'>;
}
declare module 'sematable/lib/sematable.js' {
  declare module.exports: $Exports<'sematable/lib/sematable'>;
}
declare module 'sematable/lib/SortableHeader.js' {
  declare module.exports: $Exports<'sematable/lib/SortableHeader'>;
}
declare module 'sematable/lib/Table.js' {
  declare module.exports: $Exports<'sematable/lib/Table'>;
}
declare module 'sematable/lib/TableNoData.js' {
  declare module.exports: $Exports<'sematable/lib/TableNoData'>;
}
declare module 'sematable/lib/TableRow.js' {
  declare module.exports: $Exports<'sematable/lib/TableRow'>;
}
declare module 'sematable/stories/bootstrap/v3.3.7/js/bootstrap.js' {
  declare module.exports: $Exports<'sematable/stories/bootstrap/v3.3.7/js/bootstrap'>;
}
declare module 'sematable/stories/bootstrap/v3.3.7/js/bootstrap.min.js' {
  declare module.exports: $Exports<'sematable/stories/bootstrap/v3.3.7/js/bootstrap.min'>;
}
declare module 'sematable/stories/bootstrap/v3.3.7/js/npm.js' {
  declare module.exports: $Exports<'sematable/stories/bootstrap/v3.3.7/js/npm'>;
}
declare module 'sematable/stories/bootstrap/v4.0.0/js/bootstrap.min.js' {
  declare module.exports: $Exports<'sematable/stories/bootstrap/v4.0.0/js/bootstrap.min'>;
}
declare module 'sematable/stories/button/StoryButton.js' {
  declare module.exports: $Exports<'sematable/stories/button/StoryButton'>;
}
declare module 'sematable/stories/Checkbox.js' {
  declare module.exports: $Exports<'sematable/stories/Checkbox'>;
}
declare module 'sematable/stories/common/users.js' {
  declare module.exports: $Exports<'sematable/stories/common/users'>;
}
declare module 'sematable/stories/common/UsersTable.js' {
  declare module.exports: $Exports<'sematable/stories/common/UsersTable'>;
}
declare module 'sematable/stories/common/YesNo.js' {
  declare module.exports: $Exports<'sematable/stories/common/YesNo'>;
}
declare module 'sematable/stories/default/StoryDefault.js' {
  declare module.exports: $Exports<'sematable/stories/default/StoryDefault'>;
}
declare module 'sematable/stories/default/StorySelectable.js' {
  declare module.exports: $Exports<'sematable/stories/default/StorySelectable'>;
}
declare module 'sematable/stories/editable/EditableCell.js' {
  declare module.exports: $Exports<'sematable/stories/editable/EditableCell'>;
}
declare module 'sematable/stories/editable/EditableSimpleCell.js' {
  declare module.exports: $Exports<'sematable/stories/editable/EditableSimpleCell'>;
}
declare module 'sematable/stories/editable/EditableUsersTable.js' {
  declare module.exports: $Exports<'sematable/stories/editable/EditableUsersTable'>;
}
declare module 'sematable/stories/editable/EditibleUsersTable.js' {
  declare module.exports: $Exports<'sematable/stories/editable/EditibleUsersTable'>;
}
declare module 'sematable/stories/editable/StoryEditable.js' {
  declare module.exports: $Exports<'sematable/stories/editable/StoryEditable'>;
}
declare module 'sematable/stories/editable/YesNo.js' {
  declare module.exports: $Exports<'sematable/stories/editable/YesNo'>;
}
declare module 'sematable/stories/index.js' {
  declare module.exports: $Exports<'sematable/stories/index'>;
}
