export const TOGGLE_ADD_SPONSOR = 'TOGGLE_ADD_SPONSOR'
export const TOGGLE_EDIT_DETAILS = 'TOGGLE_EDIT_DETAILS'
export const TOGGLE_DELETE_SPONSOR = 'TOGGLE_DELETE_SPONSOR'
export const TOGGLE_EDIT_QUESTIONS = 'TOGGLE_EDIT_QUESTIONS'
